### ISSUE TITLE
Configure VATER core services to read credentials from environment variables

### ISSUE THREAD

**Issue by marissaeinhorn** [dev4vater/vater#237]
Currently credentials are stored in plain text in files.  Convert to environment variables to maintain good security practices for the interim VATER solution

**Comment by marissaeinhorn** [comment]
In semaphore.py
```
 def login(self, password=None):
        if password is None:
            password=self.cfg['semaphore']['password']

        envPath = self.cfg['docker']['env_path']
        with open(envPath, "r") as f:
            lines = f.readlines()
            with open(envPath, "w") as f:
                for line in lines:
                    if 'semaphore_admin_password' not in line.strip("\n"):
                        f.write(line)
                f.write('semaphore_admin_password=' + password + '\n')

        r = self.api.s.post(
                url=self.cfg['semaphore']['api']['login'],
                data = (
                    '{'
                        '"auth": "' + self.cfg['semaphore']['user'] + '", '
                        '"password": "' + self.cfg['semaphore']['password'] + '"'
                    '}'
                )
            )
```
uses the pw to get the an API token to do the configuring
In docker-compose.yml
```
  semaphore:
    image: semaphore
    build: ./images/semaphore/
    container_name: semaphore
    environment:
      - SEMAPHORE_DB_USER=semaphore
      - SEMAPHORE_DB_PASS=semaphore
      - SEMAPHORE_DB_HOST=semaphore_db
      - SEMAPHORE_DB_PORT=3306
      - SEMAPHORE_DB=semaphore
      - SEMAPHORE_PLAYBOOK_PATH=/data/semaphore/
      - SEMAPHORE_ADMIN_PASSWORD=${semaphore_admin_password}
      - SEMAPHORE_ADMIN_NAME=admin
      - SEMAPHORE_ADMIN_EMAIL=admin@localhost
      - SEMAPHORE_ADMIN=admin
      - ANSIBLE_HOST_KEY_CHECKING=False
    volumes:
      - ./data/semaphore:/data
    networks:
      - semaphore_network
    ports:
      - "4000:3000"
    depends_on:
      - semaphore_db
    restart: always

```
Env is referenced
for semaphore PW
basically, login in semaphore.py takes a PW, by by default is none. If the PW is none it will use the semaphore password in cfg. It opens up the .env file referenced in docker-compose.yml (SEMAPHORE_ADMIN_PASSWORD=${semaphore_admin_password}) and changes the variable to whatever password is
though, because config.py makes it early on, it shouldn't be an issue

```
        cfg['docker']['env_path'] = envPath

        cfg['docker']['env'] = []

        cfg['docker']['env'].append(
            'gitea_db_user=' + cfg['gitea_db']['user']
        )

        cfg['docker']['env'].append(
            'gitea_db_password=' + cfg['gitea_db']['password']
        )

        cfg['docker']['env'].append(
            'semaphore_admin_password=' + cfg['semaphore']['password']
        )

        cfg['docker']['env'].append(
            'jenkins_admin_id=' + cfg['jenkins']['user']
        )

        cfg['docker']['env'].append(
            'jenkins_admin_password=' + cfg['jenkins']['password']
        )

        with open(envPath, 'w') as f:
            for var in cfg['docker']['env']:
                f.writelines(var + '\n')
 ```
the login process for semaphore in vater.py:
```
        if service == 'semaphore':
            s = Semaphore(config)
            s.restartContainer()
            loginSemaphore(s)
            s.setup()
```

So first the config is generated, then the container started (which is using the .env file created by config.py), then login occurs, netting the api key, and then actual configuration occurs with the api key, which was created from the admin PW
As for gitea.py
Process in vater.py is the very similar:
```
        if service == 'gitea':
            g = Gitea(config)
            g.restartContainer()
            loginGitea(g)
            g.setup()
```
Config is used to create Gitea object, then container started
the gitea service in docker-compose.yml does not allow admin user config via env
Instead, we need to use the configUser, which is the name of the admin user that is used to configure everything else. A global, system admin so to speak
The login function is responsible for ensuring this user exists
```
    def login(self, password=None):
        if password is None:
            password=self.cfg['gitea']['password']

        self.api.s.auth = (
            self.cfg['gitea']['user'],
            password
        )

        if not self.__configUserExists():
            self.__createConfigUser(password=password)

        # Confirm we can get a list of tokens, which requires auth
        r = self.api.s.get(url=self.cfg['gitea']['api']['tokens'])

        if not r.status_code == 200:
            return False

        # If the token exists, we have no way of getting the hash
        #   so remove the token
        self.__revokeConfigurationToken()

        # Get a new configuration token
        r = self.api.post(
                url=self.cfg['gitea']['api']['tokens'],
                data= '{"name": "configurationToken"}'
            )

        # Update auth header with new token
        tokenHash = json.loads(r.text)['sha1']
        self.api.s.headers.update({'Authorization': 'Token {tokenHash}'})

        return True
```
That configUserExists uses the gitea CLI to get a list of users and see if the configUser is there:
```
    def __configUserExists(self):
        # Select the config user from a list of users currently
        #   available on Gitea. Returns nothing if the user
        #   does not exist
        out = self.__giteaExecAsGit(
            'gitea admin user list | grep ' +
            self.cfg['gitea']['user'] +
            ' | tr -s \' \' | cut -d \' \' -f 2'
        )

        userFound = out.strip()

        if userFound != self.cfg['gitea']['user']:
            return False
        else:
            return True
```
If the configUser is not there, it must be created
```
    def __createConfigUser(self, password=None):
        if password is None:
            password=self.cfg['gitea']['password']

        self.__giteaExecAsGit(
            'gitea admin user create --admin'
            ' --username ' + self.cfg['gitea']['user'] +
            ' --email ' + self.cfg['gitea']['email'] +
            ' --password ' + password +
            ' --must-change-password=false'
        )
```
Once a configUser exists, we clean old API tokens (you can only get the hash needed for auth when the token is first generated, unlike semaphore, where you are always given the hash upon request)
then we get a new token and setup the gitea object to use it for future configurations
