### ISSUE TITLE
Add a task template to Create Class to reboot machine by name

### ISSUE THREAD

**Issue by uwardlaw** [dev4vater/vater#27]
- [x] Blocked by #95 
- [ ] Add `rebootVM.yml` to `rous/ansible`
- [x] Add `Reboot VM` task template to `setupNewClass.py`

**Comment by marissaeinhorn** [comment]
[Reference](https://www.robvit.com/ansible-tower-awx/ansible-vmware-playbook-examples/)  Want to stop VM, wait for 2 seconds and then power on VM instead of using built in restart option.

Stop a VM:
```
- name: VMWare tasks
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    vcenter_ip: 'VCENTERIP'
    vcenter_user: 'VCENTERUSER'
    vcenter_password: 'VCENTERPASS'
    vmname: 'VMNAME'
  tasks:
    - name: Wait for the virtual machine to shutdown
      vmware_guest_powerstate:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_password }}"
        name: "{{ vmname }}"
        validate_certs: False
        state: shutdown-guest
        state_change_timeout: 900
      register: wait
      ignore_errors: yes

    - name: ForcePoweroff 
      vmware_guest_powerstate:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_password }}"
        name: "{{ vmname }}"
        validate_certs: False
        state: powered-off
      register: poweroff
      when: wait.msg is search('Timeout')
```

Start a VM:
```
- name: VMWare tasks
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    vcenter_ip: 'VCENTERIP'
    vcenter_user: 'VCENTERUSER'
    vcenter_password: 'VCENTERPASS'
    vmname: "VMNAME"
  tasks:
    - name: ForcePowerOn
      vmware_guest_powerstate:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_password }}"
        name: "{{ vmname }}"
        validate_certs: False
        state: powered-on
```
