### ISSUE TITLE
Incorporate Packer variables in `group_vars`

### ISSUE THREAD

**Issue by uwardlaw** [dev4vater/vater#84]
- [ ] Add variables to the current templates that get called

Example groups vars from [article](https://everythingshouldbevirtual.com/automation/generatingexecuting-terraform-plans-using-ansible):

```
---
# If defining addl_disk, size is in GB
terraform_vms:
  - group: docker_lbs
    count: 2
    inventory_parent_folder: Docker
    memory_mb: 512
    naming: docker-lb
    vcpu: 1
  - group: docker_storage
    addl_disk:
      - size: 100
    count: 2
    inventory_parent_folder: Docker
    memory_mb: 512
    naming: docker-storage
    vcpu: 1
  - group: docker_swarm_managers
    count: 3
    inventory_parent_folder: Docker
    memory_mb: 1024
    naming: docker-mgr
    vcpu: 1
  - group: docker_swarm_workers
    count: 4
    inventory_parent_folder: Docker
    memory_mb: 4096
    naming: docker-wrk
    vcpu: 1
```

**Comment by rylagek** [comment]
Comparing variables between packer builders - specifically variables for:
- [ ] `vsphere-iso` 
- [ ] `virtualbox-iso`

**Comment by rylagek** [comment]
**Initial Comparison**

vsphere-iso
`virtualbox-iso`

`start N/A`
  insecure_connection = true
  vcenter_server = var.vcenter_server
  username       = var.vcenter_username
  password       = var.vcenter_password
  cluster    = var.vcenter_cluster
  datacenter = var.vcenter_datacenter
  host       = var.vcenter_host
  datastore  = var.vcenter_datastore
  folder     = var.vcenter_folder
  convert_to_template = true
  notes               = "Windows 10 Pro x64 VM template built using Packer.\nThis template is syspred and can be used for domain deployments."
  ip_wait_timeout   = "20m"
  ip_settle_timeout = "1m"
`End N/A`

`start same`
  communicator      = "winrm"
  #winrm_port             = "5985"
  winrm_timeout           = "10m"
  pause_before_connecting = "5m"
  winrm_username          = var.os_username
  winrm_password          = 
var.os_password_workstation
  vm_name              = "${var.vm_name}_${formatdate("YYYY_MM", timestamp())}"
  vm_version           = var.vm_version
  firmware             = var.vm_firmware
  guest_os_type        = var.vm_guest_os_type
`end same`

`start vboxmanage`
  CPUs                 = var.cpu_num
  CPU_hot_plug         = true
  RAM                  = var.ram
  RAM_reserve_all      = false
  RAM_hot_plug         = true
  video_ram            = "16384"
  cdrom_type           = "sata"
  disk_controller_type = ["lsilogic-sas"]

  network_adapters {
    network      = var.vm_network
    network_card = var.network_card
  }

  storage {
    disk_thin_provisioned = true
    disk_size             = var.disk_size
  }
`end vboxmanage`

`start need to test`
  iso_paths = [
    var.os_iso_path,
    var.vmtools_iso_path
  ]
`stop need to test`

`start same`
  floppy_dirs  = ["../scripts", ]
  floppy_files = ["../unattended/autounattend.xml"]

  boot_wait = "3s"
  boot_command = [
    "<spacebar><spacebar>"
  ]
`end same`

**Comment by rylagek** [comment]
New task
- [ ] write test `vboxmanage` settings to match `vcenter` settings

**Comment by uwardlaw** [comment]
Most up to date group_vars looks like this:
```
---
coreEnclave:
  switchName: switch00
  portGroupName: net00
  routerPortGroupName: net00_router
  vms:
    vyos_core_router:
      name: vyos_core_router
#      memory_mb: 1
#      vcpu: 1
#      disk: 1

windowsFundamentalsEnclave:
  switchName: switch01
  portGroupName: net01
  routerSwitchName: switch02
  routerPortGroupName: net02_router
  vms:
    vyos_fundamentals_router:
      name: vyos_fundamentals_router
      memory_mb: 1
      vcpu: 1
      disk: 1
    win10_domain:
      name: win10_domain
      memory_mb: 1
      vcpu: 1
      disk: 1
    win10_student:
      name: win10_student
      memory_mb: 1
      vcpu: 1
      disk: 1
    win2k19_AD:
      name: win2k19_AD
      memory_mb: 1
      vcpu: 1
      disk: 1
```
