### ISSUE TITLE
Add a task template to Create Class to revert machine by name

### ISSUE THREAD

**Issue by uwardlaw** [dev4vater/vater#96]
- [x] Blocked by #95 
- [x] Blocked by #82
- [ ] Add `revertVM.yml` to `rous/ansible`
- [x] Add `Revert VM` task template to `setupNewClass.py`

**Comment by marissaeinhorn** [comment]
```
- name: Revert to a snapshot
  community.vmware.vmware_guest_snapshot:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ datacenter_name }}"
    folder: "/{{ datacenter_name }}/vm/"
    name: "{{ guest_name }}"
    state: revert
    snapshot_name: snap1
  delegate_to: localhost
```
[Reference](https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_snapshot_module.html)
